import 'package:test/test.dart';

import 'package:student_app/domain/reality_layer_domain.dart';
import 'package:student_app/engines/scheduling_engine.dart' show TimeSlot;

/// STATUS: UNVERIFIED — not run through a real Dart test runner (no
/// Flutter/Dart SDK in this environment). Only `subtractOne` and
/// `isSameDate` are tested here — they are the two static helpers that
/// take no Drift-generated types (TimeSlot/DateTime only).
/// `resolveAvailabilityForDay` and `subtractConstraints` take
/// Availability/RealityConstraint (Drift codegen classes, generated by
/// build_runner, not present as plain Dart source in this repo) and so
/// cannot be unit-tested without the generated code — that gap is the
/// same standing limitation as every other repository-layer file in this
/// codebase, not specific to this file, and is a Track E
/// (build_runner + real test run) concern.
void main() {
  final day = DateTime(2026, 9, 25, 8, 0);

  group('subtractOne() — standard interval subtraction', () {
    test('no overlap leaves the slot untouched', () {
      final slot = TimeSlot(start: day, end: day.add(const Duration(hours: 2)));
      final cutStart = day.add(const Duration(hours: 5));
      final cutEnd = day.add(const Duration(hours: 6));
      final result = RealityLayerDomainService.subtractOne(slot, cutStart, cutEnd);
      expect(result, hasLength(1));
      expect(result.single.start, slot.start);
      expect(result.single.end, slot.end);
    });

    test('a cut entirely inside the slot splits it into two pieces', () {
      final slot = TimeSlot(start: day, end: day.add(const Duration(hours: 4)));
      final cutStart = day.add(const Duration(hours: 1));
      final cutEnd = day.add(const Duration(hours: 2));
      final result = RealityLayerDomainService.subtractOne(slot, cutStart, cutEnd);
      expect(result, hasLength(2));
      expect(result[0].start, slot.start);
      expect(result[0].end, cutStart);
      expect(result[1].start, cutEnd);
      expect(result[1].end, slot.end);
    });

    test('a cut covering the whole slot leaves nothing', () {
      final slot = TimeSlot(start: day, end: day.add(const Duration(hours: 2)));
      final cutStart = day.subtract(const Duration(hours: 1));
      final cutEnd = day.add(const Duration(hours: 5));
      final result = RealityLayerDomainService.subtractOne(slot, cutStart, cutEnd);
      expect(result, isEmpty);
    });

    test('a cut overlapping only the start trims the front, keeps the '
        'tail', () {
      final slot = TimeSlot(start: day, end: day.add(const Duration(hours: 4)));
      final cutStart = day.subtract(const Duration(hours: 1));
      final cutEnd = day.add(const Duration(hours: 1));
      final result = RealityLayerDomainService.subtractOne(slot, cutStart, cutEnd);
      expect(result, hasLength(1));
      expect(result.single.start, cutEnd);
      expect(result.single.end, slot.end);
    });

    test('a cut overlapping only the end trims the tail, keeps the front',
        () {
      final slot = TimeSlot(start: day, end: day.add(const Duration(hours: 4)));
      final cutStart = day.add(const Duration(hours: 3));
      final cutEnd = day.add(const Duration(hours: 6));
      final result = RealityLayerDomainService.subtractOne(slot, cutStart, cutEnd);
      expect(result, hasLength(1));
      expect(result.single.start, slot.start);
      expect(result.single.end, cutStart);
    });

    test('every returned piece has end strictly after start (never a '
        'zero-length or invalid TimeSlot)', () {
      final slot = TimeSlot(start: day, end: day.add(const Duration(hours: 8)));
      for (final cut in [
        (day.add(const Duration(hours: 1)), day.add(const Duration(hours: 1))),
        (day, day.add(const Duration(hours: 8))),
        (day.subtract(const Duration(hours: 1)), day),
      ]) {
        final result = RealityLayerDomainService.subtractOne(slot, cut.$1, cut.$2);
        for (final r in result) {
          expect(r.end.isAfter(r.start), isTrue);
        }
      }
    });
  });

  group('isSameDate()', () {
    test('same calendar day, different times -> true', () {
      expect(
        RealityLayerDomainService.isSameDate(
            DateTime(2026, 9, 25, 1), DateTime(2026, 9, 25, 23)),
        isTrue,
      );
    });

    test('different calendar day -> false', () {
      expect(
        RealityLayerDomainService.isSameDate(
            DateTime(2026, 9, 25), DateTime(2026, 9, 26)),
        isFalse,
      );
    });
  });
}
